CREATE TABLE IF NOT EXISTS `#__product_items` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`ordering` INT(11)  NOT NULL ,
`state` TINYINT(1)  NOT NULL ,
`checked_out` INT(11)  NOT NULL ,
`checked_out_time` DATETIME NOT NULL ,
`created_by` INT(11)  NOT NULL ,
`modified_by` INT(11)  NOT NULL ,
`title` VARCHAR(255)  NOT NULL ,
`alias` VARCHAR(255) COLLATE utf8_bin NOT NULL ,
`catid` INT(11)  NOT NULL ,
`code` VARCHAR(255)  NOT NULL ,
`price` VARCHAR(255)  NOT NULL ,
`old_price` VARCHAR(255)  NOT NULL ,
`intro` TEXT NOT NULL ,
`description` TEXT NOT NULL ,
`combo` VARCHAR(255)  NOT NULL ,
`combo_products` TEXT NOT NULL ,
`hot_deal` VARCHAR(255)  NOT NULL ,
`deal_price` VARCHAR(255)  NOT NULL ,
`deal_from` DATE NOT NULL ,
`deal_to` DATE NOT NULL ,
`deal_day` VARCHAR(255)  NOT NULL ,
`image_1` VARCHAR(255)  NOT NULL ,
`color` VARCHAR(255)  NOT NULL ,
`collar` VARCHAR(255)  NOT NULL ,
`sleeve` VARCHAR(255)  NOT NULL ,
`type` VARCHAR(255)  NOT NULL ,
`shape` VARCHAR(255)  NOT NULL ,
`tags` TEXT NOT NULL ,
`images` TEXT NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;

